### ISSUE TITLE
MAIL_DEFAULT_SENDER format causes a crash on Docker

### ISSUE THREAD

**Issue by avalou** [spiral-project/ihatemoney#1005]
Hello,

So I'm hosting ihm with docker, and a mariadb container for the db. If I try to create a new project, I get a 500 error and the following error stack on the server. I can anyway access to this project if I try to log into it.

```
ihatemoney_1  | ERROR [ihatemoney.run] Exception on /create [POST]
ihatemoney_1  | Traceback (most recent call last):
ihatemoney_1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
ihatemoney_1  |     response = self.full_dispatch_request()
ihatemoney_1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
ihatemoney_1  |     rv = self.handle_user_exception(e)
ihatemoney_1  |   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
ihatemoney_1  |     return original_handler(e)
ihatemoney_1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
ihatemoney_1  |     rv = self.dispatch_request()
ihatemoney_1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
ihatemoney_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ihatemoney_1  |   File "/src/ihatemoney/web.py", line 92, in admin_auth
ihatemoney_1  |     return f(*args, **kws)
ihatemoney_1  |   File "/src/ihatemoney/web.py", line 333, in create_project
ihatemoney_1  |     flash_email_error(
ihatemoney_1  |   File "/src/ihatemoney/utils.py", line 56, in flash_email_error
ihatemoney_1  |     (admin_name, admin_email) = current_app.config.get("MAIL_DEFAULT_SENDER")
ihatemoney_1  | ValueError: too many values to unpack (expected 2)
```

**Comment by avalou** [comment]
Is it related to the fact that I left default values to email related environment variables ? I do not plan to use email services.

```
      - MAIL_DEFAULT_SENDER=('Budget manager', 'admin@example.com')
      - MAIL_PASSWORD=
      - MAIL_PORT=25
      - MAIL_SERVER=localhost
      - MAIL_USE_SSL=False
      - MAIL_USE_TLS=False
      - MAIL_USERNAME=
```

**Comment by almet** [comment]
> I think we should just change this variable to be a simple string, with a format like email@address or Name <email@address>. And add a conversion from tuple to string for backwards compatibility.

I agree with this, it seems weird to have a tuple here anyway. Let's change this (and support backward compat of course) :-)
