### ISSUE TITLE
Wrong default path for configuration on Windows

### ISSUE THREAD

**Issue by pinkybae-tech** [spiral-project/ihatemoney#1069]
Recieve the following error on running command - `ihatemoney runserver`

```D:\test_ihatemoney\ihatemoney\lib\site-packages\ihatemoney\run.py:89: UserWarning: Running a server without changing the SECRET_KEY can lead to user impersonation. Please update your configuration file.
  warnings.warn(
D:\test_ihatemoney\ihatemoney\lib\site-packages\ihatemoney\run.py:44: UserWarning: The database is currently stored in /tmp and might be lost at next reboot.
  warnings.warn(
Traceback (most recent call last):
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\impl.py", line 241, in _do_get
    return self._create_connection()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 660, in __connect
    with util.safe_reraise():
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sudhi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sudhi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\test_ihatemoney\ihatemoney\Scripts\ihatemoney.exe\__main__.py", line 7, in <module>
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\flask\cli.py", line 354, in decorator
    app = __ctx.ensure_object(ScriptInfo).load_app()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\flask\cli.py", line 301, in load_app
    app = self.create_app()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\ihatemoney\run.py", line 173, in create_app
    setup_database(app)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\ihatemoney\run.py", line 55, in setup_database
    if _pre_alembic_db():
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\ihatemoney\run.py", line 37, in _pre_alembic_db
    con = db.engine.connect()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\base.py", line 104, in __init__
    else engine.raw_connection()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\base.py", line 2369, in raw_connection
    return self._wrap_pool_connect(
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\impl.py", line 241, in _do_get
    return self._create_connection()
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 660, in __connect
    with util.safe_reraise():
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "D:\test_ihatemoney\ihatemoney\lib\site-packages\sqlalchemy\engine\default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)```

**Comment by almet** [comment]
Hi, can you please specify what's your operating system and version?

**Comment by Glandos** [comment]
I tested with a non readable file and got the same error.
So it seems that the target SQLite file is not readable/writable.
Try to adjust `SQLALCHEMY_DATABASE_URI` and tell us if it's better. Or not.

**Comment by pinkybae-tech** [comment]
@almet 
> Hi, can you please specify what's your operating system and version?

![image](https://user-images.githubusercontent.com/114817652/193814698-804e3b76-3a2d-412b-a3c2-a84de33ec06a.png)

**Comment by pinkybae-tech** [comment]
> I tested with a non readable file and got the same error. So it seems that the target SQLite file is not readable/writable. Try to adjust `SQLALCHEMY_DATABASE_URI` and tell us if it's better. Or not.

@Glandos 
The code fails to access the config file. Below is the error log when error is not suppressed (silent != True) https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/run.py#L81

`FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/etc/ihatemoney\\ihatemoney.cfg'`

Had to overwrite the default settings manually with the configuration file

**Comment by Glandos** [comment]
OK, I see the issue, the default path for settings is totally non-Windows compatible: https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/run.py#L132

Question is: how to support that?

**Comment by almet** [comment]
The current supported way to run IHM on Windows is via WSL2. (Windows is not a target operating system for us)
