### ISSUE TITLE
"Internal Server Error" when creating a new project

### ISSUE THREAD

**Issue by astorije** [spiral-project/ihatemoney#109]
Hi,

When I create a new project, I get an Internal Server Error.

It seems to come from a problem when sending emails. My server (Debian Wheezy) is brand new, basically there is only nginx (and gunicorn in a virtualenv) on it. No mail server as sending emails was not needed so far.

When looking at the [Flask-Mail documentation](http://pythonhosted.org/Flask-Mail/#configuring-flask-mail), we can see that MAIL_DEFAULT_SENDER is now  DEFAULT_MAIL_SENDER. As the `requirements.txt` file does not mention a specific version of `flask-mail`, I tried both keywords in my `settings.py`. The 2 related traces are shown below.

Am I missing a dependency?

Using MAIL_DEFAULT_SENDER:
----------------
    Internal Server Error

    Traceback:

    Traceback (most recent call last):
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 126, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/var/www/ihatemoney.astori.fr/budget/web.py", line 157, in create_project
        mail.send(msg)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask_mail.py", line 416, in send
        message.send(connection)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask_mail.py", line 351, in send
        connection.send(self)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask_mail.py", line 156, in send
        "The message does not specify a sender and a default sender "
    AssertionError: The message does not specify a sender and a default sender has not been configured

Using DEFAULT_MAIL_SENDER:
-------------------
    Internal Server Error

    Traceback:

    Traceback (most recent call last):
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 126, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/var/www/ihatemoney.astori.fr/budget/web.py", line 157, in create_project
        mail.send(msg)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask_mail.py", line 416, in send
        message.send(connection)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask_mail.py
    ", line 351, in send
        connection.send(self)
      File "/var/www/ihatemoney.astori.fr/venv/local/lib/python2.7/site-packages/flask_mail.py", line 168, in send
        message.as_string())
      File "/usr/lib/python2.7/smtplib.py", line 722, in sendmail
        raise SMTPSenderRefused(code, resp, from_addr)
    SMTPSenderRefused: (501, '5.1.7 Bad sender address syntax', ('Budget manager', 'ihatemoney@astori.fr'))

**Comment by ametaireau** [comment]
This is not related to ihatemoney directly, but to your setup. You need to install correctly a postfix on your machine, or configure it to use a SMTP relay.
