### ISSUE TITLE
"Internal Server Error" on mobile device

### ISSUE THREAD

**Issue by jonathan8devs** [spiral-project/ihatemoney#1188]
**Environment:**

**Server:** Ubuntu 22.04
**iHateMoney:** via Docker & Traefik
**Did you turn it off and on:** yes

**Mobile device:** iPhone14Pro with Safari
**Notebook:** Macbook Pro 13.4.1 with Firefox

I did the update to version 6.0.0 yesterday. This has also worked so far without problems. When I opened the page in mobile view this morning, I got an "Internal Server Error". I wondered and thought maybe just the container crashed. Before I checked this, I noticed that there is no error in the browser, but only on the mobile device.

This is what is written in the Docker logs for each mobile call:
```
project_name     | ERROR [ihatemoney.run] Exception on / [GET]
project_name     | Traceback (most recent call last):
project_name     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
project_name     |     response = self.full_dispatch_request()
project_name     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
project_name     |     rv = self.handle_user_exception(e)
project_name     |   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 298, in error_router
project_name     |     return original_handler(e)
project_name     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
project_name     |     rv = self.dispatch_request()
project_name     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
project_name     |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
project_name     |   File "/src/ihatemoney/web.py", line 288, in home
project_name     |     return render_template(
project_name     |   File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
project_name     |     return _render(app, template, context)
project_name     |   File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
project_name     |     rv = template.render(context)
project_name     |   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
project_name     |     self.environment.handle_exception()
project_name     |   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
project_name     |     raise rewrite_traceback_stack(source=source)
project_name     |   File "/src/ihatemoney/templates/home.html", line 1, in top-level template code
project_name     |     {% extends "layout.html" %}
project_name     |   File "/src/ihatemoney/templates/layout.html", line 111, in top-level template code
project_name     |     {% for id, name in session['projects'].items() %}
project_name     |   File "/usr/local/lib/python3.10/site-packages/jinja2/utils.py", line 83, in from_obj
project_name     |     if hasattr(obj, "jinja_pass_arg"):
project_name     | jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
```

**Comment by zorun** [comment]
@Glandos it seems related to #1082 ? I believe we should account for existing session data that may still use a list, and convert it if required.

**Comment by haivala** [comment]
I got same error

**Comment by Glandos** [comment]
I reproduced the issue:
- git checkout a40022c~1 (before the first commit of #1082)
- create a project
- logout (important)
- go to authentication form, not from the homepage (important)
- git checkout master
- BOOM

Yes, it's #1082 that introduce a dict, and think that everything is now a dict. Session has to be cleared, but since it's from the homepage, it's a bit difficult to logout…

@haivala and @jonathan8devs you can clear your cookies as a workaround.
But I'm working on a fix to avoid a deluge of issues from migrated users.

**Comment by zorun** [comment]
Well done @Glandos , I had tried to reproduce it but couldn't, it's definitely a bit tricky!
