### ISSUE TITLE
Cannot install in dev mode with python 3.12

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#1297]
Example here in CI: https://github.com/spiral-project/ihatemoney/actions/runs/8425553353/job/23071914274

Copy of the error in case the job disappears:

```
tox -e lint
lint: install_deps> python -I -m pip install -e '.[dev]'
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "/home/runner/work/ihatemoney/ihatemoney/.tox/lint/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 167, in prepare_metadata_for_build_editable
          hook = backend.prepare_metadata_for_build_editable
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-4_xmhj5h/normal/lib/python3.12/site-packages/babel/messages/setuptools_frontend.py", line 7, in <module>
          from setuptools import Command
      ModuleNotFoundError: No module named 'setuptools'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/runner/work/ihatemoney/ihatemoney/.tox/lint/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/runner/work/ihatemoney/ihatemoney/.tox/lint/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/runner/work/ihatemoney/ihatemoney/.tox/lint/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 176, in prepare_metadata_for_build_editable
          whl_basename = build_hook(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4_xmhj5h/overlay/lib/python3.12/site-packages/hatchling/build.py", line 83, in build_editable
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4_xmhj5h/overlay/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
          build_hook.initialize(version, build_data)
        File "/home/runner/work/ihatemoney/ihatemoney/hatch_build.py", line 9, in initialize
          from babel_utils import compile_catalogs
        File "/home/runner/work/ihatemoney/ihatemoney/ihatemoney/babel_utils.py", line 3, in <module>
          from babel.messages.frontend import compile_catalog
        File "/tmp/pip-build-env-4_xmhj5h/normal/lib/python3.12/site-packages/babel/messages/frontend.py", line 1121, in __getattr__
          from babel.messages import setuptools_frontend
        File "/tmp/pip-build-env-4_xmhj5h/normal/lib/python3.12/site-packages/babel/messages/setuptools_frontend.py", line 15, in <module>
          from distutils.cmd import Command
      ModuleNotFoundError: No module named 'distutils'
```

**Comment by zorun** [comment]
@azmeuk  It looks like an issue with hatchling and/or babel, could you have a look?

In the meantime I am disabling the failing python 3.12 job in our CI.

**Comment by azmeuk** [comment]
Ah yes, we met [this in wtforms too](https://github.com/wtforms/wtforms/pull/824). The solution was to add a special setuptools dependency for python 3.12.

[Related documentation](https://github.com/python-babel/babel/blob/40e60a1f6cf178d9f57fcc14f157ea1b2ab77361/CHANGES.rst?plain=1#L22-L24)

> Babel no longer directly depends on either distutils or setuptools; if you had been
using the Babel setuptools command extensions, you would need to explicitly depend on setuptools –
though given you're running setup.py you probably already do.

@zorun do you want me to open a PR?

**Comment by zorun** [comment]
Nice, thanks. Yes, a PR would be appreciated. You can re-enable the disabled CI test in the same PR (look at "exclude:")

Out of curiosity, why does it work with older Python versions? Maybe they were bundling setuptools?

**Comment by azmeuk** [comment]
Yes, the [Python 3.12 changelog](https://docs.python.org/3/whatsnew/3.12.html) mentions it:

> [PEP 632](https://peps.python.org/pep-0632/): Remove the distutils package. See [the migration guide](https://peps.python.org/pep-0632/#migration-advice) for advice replacing the APIs it provided. The third-party [Setuptools](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html) package continues to provide distutils, if you still require it in Python 3.12 and beyond.
