### ISSUE TITLE
Path doesn't exist: 'migrations'

### ISSUE THREAD

**Issue by aavenel** [spiral-project/ihatemoney#153]
Hi, 

I tried to clone the repo from scratch and execute the usual steps : 
```
$ virtualenv venv
$ source venv/bin/activate
$ pip install -r budget/requirements.txt
$ cd budget
$ python run.py
```

Unfortunatly, I'm getting an error :

```
Traceback (most recent call last):
  File "budget/tests.py", line 16, in <module>
    import run
  File "/home/alex/Documents/dev/ihatemoney/budget/run.py", line 68, in <module>
    upgrade()
  File "/home/alex/Documents/dev/ihatemoney/venv/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 235, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/alex/Documents/dev/ihatemoney/venv/local/lib/python2.7/site-packages/alembic/command.py", line 154, in upgrade
    script = ScriptDirectory.from_config(config)
  File "/home/alex/Documents/dev/ihatemoney/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 120, in from_config
    version_locations=version_locations
  File "/home/alex/Documents/dev/ihatemoney/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 57, in __init__
    "scripts folder." % dir)
alembic.util.exc.CommandError: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
```

Should I execute another command to get started ?

**Comment by JocelynDelalande** [comment]
@aavenel reproduced your steps ; it works for me (on a fresh clone, no pre-existing venv). 

However I was able to reproduce your error if I run `python budget/run.py` (so from the parent directory), are you sure you are inside the *budget* dir when you run the command ?

**Comment by aavenel** [comment]
That was it ! I should have read the doc more carefully ... 
Thanks @JocelynDelalande !
