### ISSUE TITLE
`make release` is broken on dependencies

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#194]
Just tried to issue a `make release` (see https://github.com/spiral-project/ihatemoney/issues/180#issuecomment-290907313).

It's failing with :
```
[...]
Installing collected packages: zest.releaser, tox, colorama, six, setuptools, twine, virtualenv, pluggy, py, appdirs, packaging, clint, requests, requests-toolbelt, pkginfo, pyparsing, args
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for clint
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/packaging/requirements.py", line 9, in <module>
        from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
    ImportError: No module named 'pyparsing'
    Complete output from command /home/jocelyn/dev/ihatemoney/.venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-xcx4i2et/clint/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8h3dwuaw-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jocelyn/dev/ihatemoney/.venv/include/site/python3.4:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 72, in <module>

    import packaging.requirements

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/packaging/requirements.py", line 9, in <module>

    from pyparsing import stringStart, stringEnd, originalTextFor, ParseException

ImportError: No module named 'pyparsing'

----------------------------------------
Cleaning up...
Command /home/jocelyn/dev/ihatemoney/.venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-xcx4i2et/clint/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8h3dwuaw-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jocelyn/dev/ihatemoney/.venv/include/site/python3.4 failed with error code 1 in /tmp/pip-build-xcx4i2et/clint
Storing debug log for failure in /home/jocelyn/.pip/pip.log
Makefile:23: recipe for target '.venv/.dev_env_installed.stamp' failed
make: *** [.venv/.dev_env_installed.stamp] Error 1
```

It seems that the release venv is lacking some dependencies (zest.releaser is not pulling some things it needs). I managed to fix it by hand adding those to *dev-requirements.txt*:

```
pyparsing
requests
clint
packaging
appdirs
```

… But that seems a little weird to me to have to do that. 

@almet you seem a bit familiar with zest, what do you think ? do you experience similar issue ?

I'm using Debian Jessie.

**Comment by almet** [comment]
It seems this could be related to the version of pip you're using with Debian Jessie. One way to solve this is to upgrade the pip version that is installed in the virutalenv before actually installing the dependencies. I'll make a patch for this.

**Comment by JocelynDelalande** [comment]
> is to upgrade the pip version that is installed in the virutalenv before actually installing the dependencies. I'll make a patch for this.

Oh, nice :-) 

Do you mean patching the upstream lib or patching our README to mention that pip must be upgraded ?

**Comment by almet** [comment]
I was thinking patching the makefile :-)

**Comment by almet** [comment]
Can you give #197 a try on a clean venv @JocelynDelalande ? It's supposed to install the venv, then upgrade pip and then install the dev dependencies and dependencies. Let me know if that works better.

**Comment by JocelynDelalande** [comment]
@almet Thanks for trying :-)

However, it does not work. The error changed ! is now : 

```
[…]

Downloading/unpacking pyparsing (from packaging>=16.8->setuptools->zest.releaser->-r dev-requirements.txt (line 1))
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Installing collected packages: zest.releaser, tox, twine, setuptools, colorama, six, pluggy, virtualenv, py, pkginfo, clint, requests-toolbelt, requests, packaging, appdirs, args, pyparsing
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for clint
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named 'packaging'
    Complete output from command /home/jocelyn/dev/ihatemoney/.venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-r7t315w4/clint/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-akeig4yb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jocelyn/dev/ihatemoney/.venv/include/site/python3.4:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named 'packaging'
```

**Comment by JocelynDelalande** [comment]
@almet Thanks for trying :-)

However, it does not work. If I apply your patch, the error changes, becoming:

```
[…]

Downloading/unpacking pyparsing (from packaging>=16.8->setuptools->zest.releaser->-r dev-requirements.txt (line 1))
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Installing collected packages: zest.releaser, tox, twine, setuptools, colorama, six, pluggy, virtualenv, py, pkginfo, clint, requests-toolbelt, requests, packaging, appdirs, args, pyparsing
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for clint
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named 'packaging'
    Complete output from command /home/jocelyn/dev/ihatemoney/.venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-r7t315w4/clint/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-akeig4yb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jocelyn/dev/ihatemoney/.venv/include/site/python3.4:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named 'packaging'
```

**Comment by almet** [comment]
Can you tell me what is the pip installed version in the venv ? Seems related to https://github.com/pypa/setuptools/issues/937

**Comment by JocelynDelalande** [comment]
```
± .venv/bin/pip --version
pip 1.5.6 from /home/jocelyn/dev/ihatemoney/.venv/lib/python3.4/site-packages (python 3.4)
```

**Comment by almet** [comment]
So, I believe this is not happening anymore? Should we close?

**Comment by JocelynDelalande** [comment]
> So, I believe this is not happening anymore? Should we close?
>
I can't tell, I upgraded to stretch :-/

**Comment by JocelynDelalande** [comment]
Closing for now, until someone eventually re-open it.
