### ISSUE TITLE
Database creation doesn't seem to be working

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#248]
Since I played a bit with the import mechanism, it seems that the database creation doesn't work as it should anymore.

Steps to reproduce:

- Run the server `ihatemoney runserver`
- Open your browser at http://localhost:5000
- Click on "demo".

Here is the stacktrace I'm getting:

```
Traceback (most recent call last):
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/alexis/dev/ihatemoney/ihatemoney/utils.py", line 76, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexis/dev/ihatemoney/ihatemoney/web.py", line 340, in demo
    project = Project.query.get("demo")
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 864, in get
    return self._get_impl(ident, loading.load_on_ident)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 897, in _get_impl
    return fallback_fn(self, key)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
    return q.one()
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/alexis/dev/ihatemoney/.venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: project [SQL: 'SELECT project.id AS project_id, project.name AS project_name, project.password AS project_password, project.contact_email AS project_contact_email \nFROM project \nWHERE project.id = ?'] [parameters: ('demo',)]
```

**Comment by SuderPawel** [comment]
Similar issue noticed

```
$ IHATEMONEY_SETTINGS_FILE_PATH="$(pwd)/ihatemoney.cfg" make serve
/home/ubuntu/ihatemoney/.venv/bin/python3 -m ihatemoney.manage runserver
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> b9a10d5d63ce, Initial migration
INFO  [alembic.runtime.migration] Running upgrade b9a10d5d63ce -> 26d6a218c329, Add Person.weight column
INFO  [alembic.runtime.migration] Running upgrade 26d6a218c329 -> f629c8ef4ab0, Initialize all members weights to 1

[2017-07-17 08:12:36,276] ERROR in app: Exception on /favicon.ico/ [GET]
Traceback (most recent call last):
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: project

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/flask/app.py", line 1825, in preprocess_request
    func(request.endpoint, request.view_args)
  File "/home/ubuntu/ihatemoney/ihatemoney/web.py", line 73, in pull_project
    project = Project.query.get(project_id)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 864, in get
    return self._get_impl(ident, loading.load_on_ident)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 897, in _get_impl
    return fallback_fn(self, key)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
    return q.one()
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: project [SQL: 'SELECT project.id AS project_id, project.name AS project_name, project.password AS project_password, project.contact_email AS project_contact_email \nFROM project \nWHERE project.id = ?'] [parameters: ('favicon.ico',)]
[2017-07-17 08:12:47,845] ERROR in app: Exception on /favicon.ico/ [GET]
Traceback (most recent call last):
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/ubuntu/ihatemoney/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: project
```
