### ISSUE TITLE
Docker: SECRET_KEY = ""xxxxxxxxxxxxxxxx""  SyntaxError

### ISSUE THREAD

**Issue by mcnesium** [spiral-project/ihatemoney#322]
Cloned from this repo into `/home/docker/ihatemoney/` I am trying to run this with docker-compose:

    ihatemoney:
      container_name: ihatemoney
      build: /home/docker/ihatemoney/
      links:
        - mariadb:mariadb
      ports:
        - "127.0.0.1:8000:8000"
      environment:
        - SQLALCHEMY_DATABASE_URI = "mysql+pymysql://ihatemoney:xxxxxxxxxxxxxxxx@mariadb"
        - SECRET_KEY="xxxxxxxxxxxxxxxx"
        - MAIL_DEFAULT_SENDER="('#! money?', 'manager@ihatemoney.domain.de')"
        - MAIL_SERVER="mail.domain.de"
        - MAIL_PORT="587"
        - MAIL_USE_TLS="True"
        - MAIL_USE_SSL="True"
        - MAIL_USERNAME="ihatemoney"
        - MAIL_PASSWORD="xxxxxxxxxxxxxxxx"
        - ACTIVATE_DEMO_PROJECT="True"
        - ADMIN_PASSWORD="xxxxxxxxxxxxxxxx"
        - ALLOW_PUBLIC_PROJECT_CREATION="True"
        - ACTIVATE_ADMIN_DASHBOARD="True"

The container stops with the following log:

    $ docker logs ihatemoney
    [2018-01-31 10:09:19 +0000] [8] [INFO] Starting gunicorn 19.7.[2018-01-31 10:09:19 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
    [2018-01-31 10:09:19 +0000] [8] [INFO] Using worker: sync
    [2018-01-31 10:09:19 +0000] [11] [INFO] Booting worker with pid: 11
    [2018-01-31 10:09:19 +0000] [12] [INFO] Booting worker with pid: 12
    [2018-01-31 10:09:19 +0000] [13] [INFO] Booting worker with pid: 13
    [2018-01-31 10:09:21 +0000] [13] [ERROR] invalid syntax (ihatemoney.cfg, line 5)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
        self.wsgi = self.app.wsgi()
      File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
        self.callable = self.load()
      File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
        return self.load_wsgiapp()
      File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
        return util.import_app(self.app_uri)
      File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
        __import__(module)
      File "/ihatemoney/ihatemoney/wsgi.py", line 3, in <module>
        application = create_app()
      File "/ihatemoney/ihatemoney/run.py", line 114, in create_app
        load_configuration(app, configuration)
      File "/ihatemoney/ihatemoney/run.py", line 70, in load_configuration
        app.config.from_pyfile('ihatemoney.cfg', silent=True)
      File "/usr/local/lib/python3.6/site-packages/flask/config.py", line 130, in from_pyfile
        exec(compile(config_file.read(), filename, 'exec'), d.__dict__)
      File "/etc/ihatemoney/ihatemoney.cfg", line 5
        SECRET_KEY = ""xxxxxxxxxxxxxxxx""
                                      ^
    SyntaxError: invalid syntax

    During handling of the above exception, another exception occurred:

    […this repeats a couple of times…]

    [2018-01-31 10:09:21 +0000] [12] [INFO] Worker exiting (pid: 12)
    [2018-01-31 10:09:21 +0000] [8] [INFO] Shutting down: Master
    [2018-01-31 10:09:21 +0000] [8] [INFO] Reason: Worker failed to boot.

Key question: where do those two double quotes arise from.
Sidenote: this also happens if there are no doublequotes in docker-compose.yml at the `SECRET_KEY` envvar

**Comment by almet** [comment]
Did you manage to make it run in the end?

**Comment by 0livd** [comment]
Hey @mcnesium ,

I was able to make the following docker-compose.yml work with docker-compose v1.20

    version: '3'
    services:
      ihatemoney:
        container_name: ihatemoney
        build: .
        ports:
          - "127.0.0.1:8000:8000"
        environment:
          - SQLALCHEMY_DATABASE_URI = mysql+pymysql://ihatemoney:xxxxxxxxxxxxxxxx@mariadb
          - SECRET_KEY=xxxxxxxxxxxxxxxx
          - MAIL_DEFAULT_SENDER=('#! money?', 'manager@ihatemoney.domain.de')
          - MAIL_SERVER=mail.domain.de
          - MAIL_PORT=587
          - MAIL_USE_TLS=True
          - MAIL_USE_SSL=True
          - MAIL_USERNAME=ihatemoney
          - MAIL_PASSWORD=xxxxxxxxxxxxxxxx
          - ACTIVATE_DEMO_PROJECT=True
          - ADMIN_PASSWORD=pbkdf2:sha256:50000$$CLCBSCdb$$2e9cf8431cc52a5efdbb1cd915f6882e7cf9aa7efca516aa01d41316b1c72828
          - ALLOW_PUBLIC_PROJECT_CREATION=True
          - ACTIVATE_ADMIN_DASHBOARD=True

First, don't put double quotes around the environment variables values because some of them are used as python keywords (e.g. `True`) in a python config file. 
Then, the password you generated with `ihatemoney generate_password` contains `$`s. You need to escape them with another `$` so docker doesn't interpret them as variables. See https://docs.docker.com/compose/compose-file/#variable-substitution
Very tricky, as always with docker...

**Comment by mcnesium** [comment]
Thank you for replying, this helped. …and took me straigth to the next issue #394
