### ISSUE TITLE
`ihatemoney` command should not hide stderr

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#330]
I followed the [documentation](https://ihatemoney.readthedocs.io/en/latest/upgrade.html) to upgrade from 1.0 to 2.1.  I created a new virtualenv and installed ihatemoney 2.1 in it:

```
$ virtualenv venv
$ . venv/bin/activate
$ pip install ihatemoney
$ ihatemoney generate-config
$
```

However, I was puzzled because the `ihatemoney generate-config` command output nothing, and did not seem to create any file.

After playing a bit and reading the code:

```
$ ihatemoney -h
Traceback (most recent call last):
  File "/home/budget/venv3/bin/ihatemoney", line 11, in <module>
    sys.exit(main())
  File "/home/budget/venv3/lib/python3.5/site-packages/ihatemoney/manage.py", line 68, in main
    app = create_app()
  File "/home/budget/venv3/lib/python3.5/site-packages/ihatemoney/run.py", line 127, in create_app
    setup_database(app)
  File "/home/budget/venv3/lib/python3.5/site-packages/ihatemoney/run.py", line 44, in setup_database
    if _pre_alembic_db():
  File "/home/budget/venv3/lib/python3.5/site-packages/ihatemoney/run.py", line 26, in _pre_alembic_db
    con = db.engine.connect()
  File "/home/budget/venv3/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 877, in engine
    return self.get_engine()
  File "/home/budget/venv3/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/home/budget/venv3/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 559, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/home/budget/venv3/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/budget/venv3/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 81, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/budget/venv3/lib/python3.5/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 584, in dbapi
    import psycopg2
ImportError: No module named 'psycopg2'
```

First, I am not sure why it tries to load psycopg2, but it's indeed a missing dependency in my case because I used Postgresql with ihatemoney 1.0.

Second, it seems that the script purposefully tries to hide `stderr` to avoid confusing users, but it had the opposite effect on me :) It seems to be a bad idea in general...

**Comment by almet** [comment]
Here is a related discussion we had about this: https://github.com/spiral-project/ihatemoney/issues/277
