### ISSUE TITLE
500 error (session serialisation issue) after upgrading from 1.0 to 2.1

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#331]
I did the following:

- upgrade from 1.0 to 2.1, following the [instructions](https://ihatemoney.readthedocs.io/en/latest/upgrade.html)
- take the opportunity to switch from python2 to python3 (new virtualenv on Debian stretch)

However, I got a 500 error when I first loaded the new version of Ihatemoney with Firefox.  Here is the traceback:

```
[2018-03-15 23:36:42,651] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/budget/venv3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/budget/venv3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/budget/venv3/lib/python3.5/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/budget/venv3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/budget/venv3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/budget/venv3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/budget/venv3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/budget/venv3/lib/python3.5/site-packages/ihatemoney/web.py", line 203, in home
    project_form = ProjectForm()
  File "/home/budget/venv3/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/budget/venv3/lib/python3.5/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/budget/venv3/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/budget/venv3/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/budget/venv3/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/budget/venv3/lib/python3.5/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/budget/venv3/lib/python3.5/site-packages/flask_wtf/csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "/home/budget/venv3/lib/python3.5/site-packages/itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/home/budget/venv3/lib/python3.5/site-packages/itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/home/budget/venv3/lib/python3.5/site-packages/itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/home/budget/venv3/lib/python3.5/site-packages/itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'0123456789abcdef0123456789abcdef012345678' is not JSON serializable
```
(I have obviously scrambled the actual hexadecimal value at the end, since I don't know whether it is sensitive)

Since this looks like an issue with an old session or cookie, I restarted Firefox and everything went back to normal.  But it's still an annoying issue.

**Comment by almet** [comment]
I think it's a matter of having stuff stored in the session that's not compatible after the upgrade. If you want to have a better look at it, don't hesitate, I don't know what to do with it so far :)
