### ISSUE TITLE
Document unicode settings for postgresql Database

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#403]
Not sure why?!

**Comment by almet** [comment]
On the hosted version, when you add a new bill.

**Comment by almet** [comment]
```python
ERROR [flask.app] Exception on /boner/add [POST]
Traceback (most recent call last):
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/web.py", line 499, in add_bill
    db.session.commit()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe8' in position 2: ordinal not in range(128)

```

**Comment by 0livd** [comment]
Hey, it seems that Sqlalchemy has somehow detected that it should talk to your database engine in ASCII. You should check your database config to see which encodings it accepts or maybe try to tune Sqlalchemy settings to force an encoding.

**Comment by JocelynDelalande** [comment]
So is this something we can handle/enhance on our side ?

**Comment by almet** [comment]
It seems there are multiple ways to solve this:
- by changing the configuration on the deployed server (which I just did, but haven't tested yet if it solves the problem)
- by enforcing the encoding of the connection, but after a quick look I didn't find how to do so with our codebase.

**Comment by almet** [comment]
Actually just tested and it seems solved by my config change.

**Comment by JocelynDelalande** [comment]
> Actually just tested and it seems solved by my config change.

Maybe it is relevant to document it in our manual for postgresql configs ?

**Comment by almet** [comment]
It is!

FTR, I've added `?client_encoding=utf8` to the connection string.
