### ISSUE TITLE
Internal Server Error on CSV export

### ISSUE THREAD

**Issue by truenicoco** [spiral-project/ihatemoney#436]
Trying to export bills or settlements in [this project](https://ihatemoney.org/evg-didou) returns a 500 error. I am using the standard web interface.

**Comment by almet** [comment]
Hi, thanks for the report. I'm marking this as a bug. Can you provide some information about your project, maybe giving us a JSON export? (if it works?)

**Comment by truenicoco** [comment]
JSON also produces a 500 error. I could give you the password to the project in private if you are interested.
About the project: 19 members with different shares, around 20 bills.

**Comment by almet** [comment]
Hi, that would be helpful to get an access there, yes! Can you send me an email at alexis at notmyidea org ? Thanks !

**Comment by almet** [comment]
Here is a traceback info I got from the server :
```
Traceback (most recent call last):
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/web.py", line 340, in edit_project
    as_attachment=True
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/helpers.py", line 592, in send_file
    data = wrap_file(request.environ, file)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/werkzeug/wsgi.py", line 893, in wrap_file
    return environ.get('wsgi.file_wrapper', FileWrapper)(file, buffer_size)
```

**Comment by truenicoco** [comment]
I just sent you an email. Thanks!

**Comment by almet** [comment]
Sorry for the delay on this. I've investigated this evening. It seems we're hitting [this issue](https://github.com/unbit/uwsgi/issues/1126).

So it's not an issue in ihatemoney itself, but in uwsgi. I've solved the issue by appending

```
wsgi-disable-file-wrapper = true
```

At the end of the uwsgi.conf file.
