### ISSUE TITLE
Encoding error when running pip install ihatemoney

### ISSUE THREAD

**Issue by Thaega** [spiral-project/ihatemoney#465]
Running pip install ihatemoney yields the following error: 
```# > pip3 install ihatemoney
Collecting ihatemoney
  Using cached https://files.pythonhosted.org/packages/9d/aa/ed29f19ee8fbbe7cb0f64591018073f6361c4bd0ed444943e5c3462b3d7e/ihatemoney-4.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /data/ihatemoney/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q80z4f2s/ihatemoney/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q80z4f2s/ihatemoney/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info                                                                                                                         
         cwd: /tmp/pip-install-q80z4f2s/ihatemoney/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q80z4f2s/ihatemoney/setup.py", line 21, in <module>
        README = read_file('README.rst')
      File "/tmp/pip-install-q80z4f2s/ihatemoney/setup.py", line 11, in read_file
        return f.read()
      File "/data/ihatemoney/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 197: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
This error could be solved by running instead `LC_CTYPE=C.UTF-8 pip3 install ihatemoney`, however I think it should be fixed at code level.

**Comment by gbip** [comment]
I have the same issue on FreeBSD.

**Comment by almet** [comment]
Thanks to both of you for the info. However, I'm not able to reproduce on my system (debian 10 & pip `19.2.3`). Investigating.

**Comment by almet** [comment]
@gbip and @Thaega can you try #468 and tell me if it solves your issue? thanks!
