### ISSUE TITLE
Settle - Internal Server Error

### ISSUE THREAD

**Issue by fruffy** [spiral-project/ihatemoney#508]
Hello,
great website. We set up a project and would like to settle bills. Unfortunately, clicking on the link ("settle") leads to an internal server error. Do you know what the cause of this could be?

**Comment by almet** [comment]
Hi,
 
Thanks for taking the time to report the issue. Can you please give me your project identifier so I can have a look? Thanks! 

Fri Nov 01 16:53:15 GMT+01:00 2019 fruffy <notifications@github.com>:

**Comment by fruffy** [comment]
Sure, it is nyusystemcoffee

**Comment by almet** [comment]
So, it seems we have a bug in `debts`!

```ERROR [flask.app] Exception on /nyusystemcoffee/settle_bills [GET]
Traceback (most recent call last):
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/web.py", line 566, in settle_bill
    bills = g.project.get_transactions_to_settle_bill()
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/models.py", line 111, in get_transactions_to_settle_bill
    settle_plan = settle(self.balance.items()) or []
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/debts/solver.py", line 11, in settle
    check_balance(debiters, crediters)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/debts/solver.py", line 27, in check_balance
    sum_debiters=sum_debiters
debts.solver.UnbalancedRequest: Unsolvable : debiters (-63.85) and crediters (+63.82) are unbalanced.
```

**Comment by almet** [comment]
cc @Natim, it seems we need to find a better way to handle this!

**Comment by almet** [comment]
@fruffy, I'm not sure exactly what's happening.

Could you please do an export of your project (settings, then export) and send it to me by email? use alexis  notmyidea org? that would help me understand what's going on. thanks!

**Comment by almet** [comment]
Also, giving me the access code by email would help :-)

**Comment by fruffy** [comment]
Did you receive the email?

**Comment by almet** [comment]
Yes :)

**Comment by eMerzh** [comment]
@almet the demo in IHM.org is also affected

https://ihatemoney.org/demo/settle_bills

**Comment by Natim** [comment]
Rounding errors

**Comment by almet** [comment]
Yep, I've just issued a point release for debts, that should be it! https://framagit.org/almet/debts/commit/09ee167cf0b265610d92bba28fbf4354d4b8b53a

(Currently deploying the fix)

**Comment by almet** [comment]
And… the show is over :-)
