### ISSUE TITLE
Fresh install breaks because of dependency Werkzeug 1.0

### ISSUE THREAD

**Issue by Shaac** [spiral-project/ihatemoney#540]
Hello,

I just did a fresh installation, following the documentation, namely a new python virtualenv, and then `pip install ihatemoney`.

```
Traceback (most recent call last):                                                                                                      
  File "/usr/share/webapps/ihatemoney/bin/ihatemoney", line 11, in <module>                                                             
    load_entry_point('ihatemoney==4.1.3', 'console_scripts', 'ihatemoney')()   
  File "/usr/share/webapps/ihatemoney/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point             
    return get_distribution(dist).load_entry_point(group, name)                                                                         
  File "/usr/share/webapps/ihatemoney/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point            
    return ep.load()                                                                                                                      File "/usr/share/webapps/ihatemoney/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load                        
    return self.resolve()                                                                                                               
  File "/usr/share/webapps/ihatemoney/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve                     
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                               
  File "/usr/share/webapps/ihatemoney/lib/python3.8/site-packages/ihatemoney/manage.py", line 12, in <module>
    from ihatemoney.run import create_app
  File "/usr/share/webapps/ihatemoney/lib/python3.8/site-packages/ihatemoney/run.py", line 9, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.contrib'
```

It seems that the new realease of Werkzeug 1.0, 3 weeks ago, changed their API. I’ve seen that in requirements.txt, the specified version is 0.16, but `pip install ihatemoney` seems to have downloaded the 1.0 version.

I was able to fix the issue locally by doing

```
pip uninstall Werkzeug 
pip install Werkzeug==0.16
``` 

So now it works fine for me, but this should be fixed (probably but upgrading to Werkzeug 1.0) so that following readme instruction do not lead to a broken installation.

For information, I use python 3.8 on archlinux.

**Comment by gr8temi** [comment]
Hi @Glandos I would love to fix this bug for you

**Comment by Glandos** [comment]
[**@gr8temi**](https://github.com/gr8temi) commented on [4 mars 2020 à 19:56 UTC+1](https://github.com/spiral-project/ihatemoney/issues/540#issuecomment-594751554 "2020-03-04T18:56:43Z - Replied by Github Reply Comments"):
> Hi I would love to fix this bug for you

Please do :)

**Comment by JocelynDelalande** [comment]
I can confirm the bug ; that does not only affect current master but also stable release 4.1.3 (probably any fresh install and upgrade).

**Comment by Natim** [comment]
Too bad tests are passing with this bug.

**Comment by Natim** [comment]
I just tried with 1.0.1 and everything looks fixed.

**Comment by zorun** [comment]
I just tried installing a fresh ihatemoney 4.1.3 on Buster and I still have the issue:

```
Traceback (most recent call last):
  File "/home/budget/venv3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/budget/venv3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/budget/venv3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/budget/venv3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/budget/venv3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/budget/venv3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/budget/venv3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/budget/venv3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/budget/venv3/lib/python3.7/site-packages/ihatemoney/wsgi.py", line 1, in <module>
    from ihatemoney.run import create_app
  File "/home/budget/venv3/lib/python3.7/site-packages/ihatemoney/run.py", line 9, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.contrib'
```

Here is a pip freeze in the virtualenv:

```
(venv3) budget@budget:~$ pip freeze
alembic==1.4.2
aniso8601==8.0.0
Babel==2.8.0
blinker==1.4
click==7.1.1
dnspython==1.16.0
email-validator==1.0.5
Flask==1.1.2
Flask-Babel==1.0.0
Flask-Cors==3.0.8
Flask-Mail==0.9.1
Flask-Migrate==2.5.3
Flask-RESTful==0.3.8
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.1
Flask-WTF==0.14.3
gunicorn==20.0.4
idna==2.9
ihatemoney==4.1.3
itsdangerous==1.1.0
Jinja2==2.11.2
Mako==1.1.2
MarkupSafe==1.1.1
pkg-resources==0.0.0
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2019.3
six==1.14.0
SQLAlchemy==1.3.16
Werkzeug==1.0.1
WTForms==2.3.1
```

So, I believe werkzeug 1.0.1 does not fix the issue. Manually downgrading to 0.16did.
