### ISSUE TITLE
dev env setup fails

### ISSUE THREAD

**Issue by baizsof** [spiral-project/ihatemoney#542]
Hey, 

I just found this repo, the idea is great, I would like to contribute. 

I followed instruction from here: https://ihatemoney.readthedocs.io/en/latest/contributing.html

1. Cloned the repo
2. installed the requirements inside requirements.txt
3. gave command python run.py

And got the following error. 
```python stacktrace
D:\dev\ihatemoney\ihatemoney>python run.py
run.py:83: UserWarning: Running a server without changing the SECRET_KEY can lead to user impersonation. Please update your configuration file.
  warnings.warn(
run.py:38: UserWarning: The database is currently stored in /tmp and might be lost at next reboot.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\impl.py", line 238, in _do_get
    return self._create_connection()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 173, in <module>
    main()
  File "run.py", line 168, in main
    app = create_app()
  File "run.py", line 139, in create_app
    setup_database(app)
  File "run.py", line 49, in setup_database
    if _pre_alembic_db():
  File "run.py", line 31, in _pre_alembic_db
    con = db.engine.connect()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 2206, in connect
    return self._connection_cls(self, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 103, in __init__
    else engine.raw_connection()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 2305, in raw_connection
    return self._wrap_pool_connect(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 2278, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\impl.py", line 238, in _do_get
    return self._create_connection()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by almet** [comment]
Can you please paste the configuration file you're using? Thanks!

**Comment by baizsof** [comment]
> Can you please paste the configuration file you're using? Thanks!

Hey, thanks for the rapid reply. I have not change the config file at all. Using the default settings, which are the dev env settings stated in the config file.

**Comment by baizsof** [comment]
Is any other preparation required for dev env then the following one? 

`git clone https://github.com/spiral-project/ihatemoney.git
pip install -r requirements.txt
pip install -e .
cd ihatemoney
python run.py`

**Comment by almet** [comment]
I believe this is because you're running windows. By default, the database is supposed to be in /tmp, which doesn't exist on windows.

I'm not sure if we're currently supporting windows, I've never had any feedback about it, and my knowledge of this OS is fairly low. In order to make this work, I believe you would need to generate a configuration file (see the docs for this) and then point the "IHATEMONEY_SETTINGS_FILE_PATH" variable to your configuration, which would have the correct database path.

**Comment by jdckr** [comment]
I don't know if it is worth to get it running on Windows. Setup WSL and you're good to go. Still you can access the files from Windows and use your favorite IDE.

**Comment by GateauXD** [comment]
I ran into the same problem that @baizsof had and using WSL instead of trying to install directly on windows worked. 

In WSL I used:
```
make serve
```
and everything worked properly

**Comment by almet** [comment]
Thanks! Closing :-)
