### ISSUE TITLE
migration fails from empty postgresql database

### ISSUE THREAD

**Issue by symphorien** [spiral-project/ihatemoney#577]
I'm updating the ihatemoney package in NixOS from 4.1.3 to 4.2 and the automated tests fail when the backend is postgresql.

The full error is here, and happens on a freshly created and empty postgresql database.
```
 [   41.928252] uwsgi[898]: INFO  [alembic.runtime.migration] Running upgrade f629c8ef4ab0 -> b78f8a8bdb16, hash project passwords
machine # [   41.935319] uwsgi[898]: INFO  [alembic.runtime.migration] Running upgrade b78f8a8bdb16 -> afbf27e6ef20, add bill.import_date field
machine # [   41.945859] uwsgi[898]: INFO  [alembic.runtime.migration] Running upgrade afbf27e6ef20 -> a67119aa3ee5, Migrate negative weights
machine # [   41.949431] uwsgi[898]: INFO  [alembic.runtime.migration] Running upgrade a67119aa3ee5 -> 6c6fb2b7f229, empty message
machine # [   41.952199] uwsgi[898]: INFO  [alembic.runtime.migration] Running upgrade 6c6fb2b7f229 -> 2dcb0c0048dc, autologger
machine # [   48.534793] uwsgi[898]: INFO  [alembic.runtime.migration] Running upgrade 2dcb0c0048dc -> cb038f79982e, sqlite_autoincrement
machine # [   48.548668] uwsgi[898]: INFO  [alembic.ddl.postgresql] Detected sequence named 'person_id_seq' as owned by integer column 'person(id)', assuming SERIAL and omitting
machine # [   48.588016] 0aa9vklp7ixf9yy5566zs2dyyif62nj8-unit-script-postgresql-start[756]: 2020-04-24 21:36:37.886 GMT [905] ERROR:  cannot drop constraint person_pkey on table person because other objects depend on it
machine # [   48.602735] 0aa9vklp7ixf9yy5566zs2dyyif62nj8-unit-script-postgresql-start[756]: 2020-04-24 21:36:37.886 GMT [905] DETAIL:  constraint bill_payer_id_fkey on table bill depends on index person_pkey
machine # [   48.610678] 0aa9vklp7ixf9yy5566zs2dyyif62nj8-unit-script-postgresql-start[756]:    constraint billowers_person_id_fkey on table billowers depends on index person_pkey
machine # [   48.618928] 0aa9vklp7ixf9yy5566zs2dyyif62nj8-unit-script-postgresql-start[756]: 2020-04-24 21:36:37.886 GMT [905] HINT:  Use DROP ... CASCADE to drop the dependent objects too.
machine # [   48.625704] 0aa9vklp7ixf9yy5566zs2dyyif62nj8-unit-script-postgresql-start[756]: 2020-04-24 21:36:37.886 GMT [905] STATEMENT:  ALTER TABLE person DROP CONSTRAINT person_pkey
machine # [   48.635978] uwsgi[898]: Traceback (most recent call last):
machine # [   48.642193] uwsgi[898]:   File "/nix/store/g3icgm6a2fm7zdi6mxjgipg28zl9f71z-python3-3.7.7-env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
machine # [   48.648675] uwsgi[898]:     cursor, statement, parameters, context
machine # [   48.653803] uwsgi[898]:   File "/nix/store/g3icgm6a2fm7zdi6mxjgipg28zl9f71z-python3-3.7.7-env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
machine # [   48.658809] uwsgi[898]:     cursor.execute(statement, parameters)
machine # [   48.663671] uwsgi[898]: psycopg2.errors.DependentObjectsStillExist: cannot drop constraint person_pkey on table person because other objects depend on it
machine # [   48.670368] uwsgi[898]: DETAIL:  constraint bill_payer_id_fkey on table bill depends on index person_pkey
machine # [   48.675578] uwsgi[898]: constraint billowers_person_id_fkey on table billowers depends on index person_pkey
machine # [   48.679825] uwsgi[898]: HINT:  Use DROP ... CASCADE to drop the dependent objects too.
machine # [   48.684085] uwsgi[898]: The above exception was the direct cause of the following exception:
machine # [   48.687656] uwsgi[898]: Traceback (most recent call last):
machine # [   48.690423] uwsgi[898]:   File "./wsgi.py", line 3, in <module>
machine # [   48.694735] uwsgi[898]:     application = create_app()
machine # [   48.700460] uwsgi[898]:   File "/nix/store/g3icgm6a2fm7zdi6mxjgipg28zl9f71z-python3-3.7.7-env/lib/python3.7/site-packages/ihatemoney/run.py", line 138, in create_app
machine # [   48.706902] uwsgi[898]:     setup_database(app)
machine # [   48.710656] uwsgi[898]:   File "/nix/store/g3icgm6a2fm7zdi6mxjgipg28zl9f71z-python3-3.7.7-env/lib/python3.7/site-packages/ihatemoney/run.py", line 55, in setup_database
machine # [   48.716917] uwsgi[898]:     upgrade(migrations_path)
machine # [   48.725901] uwsgi[898]:   File "/nix/store/g3icgm6a2fm7zdi6mxjgipg28zl9f71z-python3-3.7.7-env/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
machine # [   48.735653] uwsgi[898]:     f(*args, **kwargs)
machine # [   48.738573] uwsgi[898]:   File "/nix/store/g3icgm6a2fm7zdi6mxjgipg28zl9f71z-python3-3.7.7-env/lib/python3.7/site-packages/flask_migrate/__init__.py", line 280, in upgrade
machine # [   48.742851] uwsgi[898]:     command.upgrade(config, revision, sql=sql, tag=tag)
machine # [   48.746828] uwsgi[898]:   File "/nix/store/g3icgm6a2fm7zdi6mxjgipg28zl9f71z-python3-3.7.7-env/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
machine # [   48.751049] uwsgi[898]:     script.run_env()
```

This does not happen on 4.1.3 or with the sqlite backend.

**Comment by Natim** [comment]
@symphorien thank you very much for this early bug report. I guess that the kind of feedback we were needing for this release.

I know that Alembic sometimes is having issues auto generating migrations and they need to be improved by hand.

**Comment by Natim** [comment]
Can you tell me if #579 fixes the issue?

**Comment by symphorien** [comment]
Yes this fixes the migration and the test now passes.
Note that it's really simplistic (it only creates an empty project) : https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/ihatemoney.nix#L28-L30

**Comment by zorun** [comment]
Hi @symphorien , I noticed that you use 4.2 for the Nix package.  The 4.2 tag was a mistake, the next major version will be 5.0 and it's not ready yet.

We have published a bugfix release 4.1.4 on pypi some weeks ago, but we forgot to push the tag on github. It's now done. You should use this version for the Nix package.

**Comment by symphorien** [comment]
Is it possible to downgrade from 4.2 to 4.1.4 without database shenanigans? If not, I am afraid that downgrading is a no-no.

**Comment by zorun** [comment]
It's supposed to be possible:

```bash
cd ihatemoney
./manage.py db downgrade a67119aa3ee5
```

However, it's probably completely untested. I just tried from latest master and it breaks with sqlite:

```
INFO  [alembic.runtime.migration] Running downgrade 927ed575acbd -> cb038f79982e, Add currencies

sqlite3.OperationalError: near "DROP": syntax error

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DROP": syntax error
[SQL: ALTER TABLE project_version DROP COLUMN default_currency]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

Apparently sqlite does not support dropping columns... https://code.i-harness.com/en/q/1cfc76e
