### ISSUE TITLE
Salt is required for PBKDF2

### ISSUE THREAD

**Issue by kduchrow** [spiral-project/ihatemoney#679]
Hi, I am trying to deploy ihatmoney with docker-compose. 
After struggeling with the admin Password, I generated a working Admin PW. 
Now after logging in to the admin dashboard, i am getting this error : 

```
l-validator-1.0.4 idna-2.10 ihatemoney-4.1.5 itsdangerous-1.1.0 python-dateutil-2.8.1 python-editor-1.0.4 pytz-2020.1 six-1.14.0
ihatemoney_1  | [2020-09-17 11:32:53 +0000] [1] [INFO] Starting gunicorn 20.0.4
ihatemoney_1  | [2020-09-17 11:32:53 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
ihatemoney_1  | [2020-09-17 11:32:53 +0000] [1] [INFO] Using worker: sync
ihatemoney_1  | [2020-09-17 11:32:53 +0000] [65] [INFO] Booting worker with pid: 65
ihatemoney_1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
ihatemoney_1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ihatemoney_1  | ERROR [ihatemoney.run] Exception on /admin [POST]
ihatemoney_1  | Traceback (most recent call last):
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
ihatemoney_1  |     response = self.full_dispatch_request()
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
ihatemoney_1  |     rv = self.handle_user_exception(e)
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
ihatemoney_1  |     return original_handler(e)
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
ihatemoney_1  |     reraise(exc_type, exc_value, tb)
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
ihatemoney_1  |     raise value
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
ihatemoney_1  |     rv = self.dispatch_request()
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
ihatemoney_1  |     return self.view_functions[rule.endpoint](**req.view_args)
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/ihatemoney/web.py", line 138, in admin
ihatemoney_1  |     form.admin_password.data)):
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/werkzeug/security.py", line 221, in check_password_hash
ihatemoney_1  |     return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
ihatemoney_1  |   File "/usr/local/lib/python3.7/site-packages/werkzeug/security.py", line 152, in _hash_internal
ihatemoney_1  |     raise ValueError("Salt is required for PBKDF2")
ihatemoney_1  | ValueError: Salt is required for PBKDF2
```

Thank You for helping!

**Comment by Glandos** [comment]
It seems that the value for `ADMIN_PASSWORD` is not correct. Did you generate your password with `ihatemoney generate_password_hash` or another tool?

**Comment by kduchrow** [comment]
I tried it with other tools, but it won't work at all. 
After I used the `ihatemoney generate_password_hash` tool, I got the message I've shown above.

**Comment by Glandos** [comment]
Can you try to enter a dumb password like `test`, and copy/paste the output here for me to test?

**Comment by kduchrow** [comment]
Sure,

```
/ # ihatemoney generate_password_hash
Password: (test)
pbkdf2:sha256:150000$HDAyBoP3$7d4c52ab93d8a956eba35d6f714885fb38bd100cd4dcbbd251b608d2c251bafa
```

**Comment by kduchrow** [comment]
Okay, I fexed it. Obiousily you don't need any quotes or double $ if using .env file in Docker-Compose. 

I tested this Line and it worked ...

`ADMIN_PASSWORD=pbkdf2:sha256:150000$HDAyBoP3$7d4c52ab93d8a956eba35d6f714885fb38bd100cd4dcbbd251b608d2c251bafa`
