### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError on clean installation with docker

### ISSUE THREAD

**Issue by nkoester** [spiral-project/ihatemoney#713]
I setup ihatemoney on my local machine and for the use in my local network using docker. I am on the nightly build and navigating to the history gives me an ```Internal Server Error```. On console the docker container logs the following.

<details>
  <summary>Click to show error message</summary>
  
```bash
ihatemoney    | ERROR [ihatemoney.run] Exception on /test/history [GET]
ihatemoney    | Traceback (most recent call last):
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
ihatemoney    |     response = self.full_dispatch_request()
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
ihatemoney    |     rv = self.handle_user_exception(e)
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
ihatemoney    |     return original_handler(e)
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
ihatemoney    |     reraise(exc_type, exc_value, tb)
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
ihatemoney    |     raise value
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
ihatemoney    |     rv = self.dispatch_request()
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
ihatemoney    |     return self.view_functions[rule.endpoint](**req.view_args)
ihatemoney    |   File "/ihatemoney/ihatemoney/web.py", line 795, in history
ihatemoney    |     current_log_pref=g.project.logging_preference,
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
ihatemoney    |     ctx.app,
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
ihatemoney    |     rv = template.render(context)
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
ihatemoney    |     self.environment.handle_exception()
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
ihatemoney    |     reraise(*rewrite_traceback_stack(source=source))
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
ihatemoney    |     raise value.with_traceback(tb)
ihatemoney    |   File "/ihatemoney/ihatemoney/templates/history.html", line 96, in top-level template code
ihatemoney    |     {{ _("owers list") }}
ihatemoney    |   File "/ihatemoney/ihatemoney/templates/sidebar_table_layout.html", line 40, in top-level template code
ihatemoney    |     {% if balance[member.id] | round(2) > 0 %}+{% endif %}{{ balance[member.id]|currency }}
ihatemoney    |   File "/ihatemoney/ihatemoney/templates/layout.html", line 123, in top-level template code
ihatemoney    |     {% block body %}
ihatemoney    |   File "/ihatemoney/ihatemoney/templates/sidebar_table_layout.html", line 54, in block "body"
ihatemoney    |     {% block content %}{% endblock %}
ihatemoney    |   File "/ihatemoney/ihatemoney/templates/history.html", line 164, in block "content"
ihatemoney    |     <td>{{ event.time|datetimeformat("medium") }}</td>
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask_babel/__init__.py", line 394, in format_datetime
ihatemoney    |     return _date_format(dates.format_datetime, datetime, format, rebase)
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask_babel/__init__.py", line 463, in _date_format
ihatemoney    |     extra['tzinfo'] = get_timezone()
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask_babel/__init__.py", line 270, in get_timezone
ihatemoney    |     tzinfo = babel.default_timezone
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/flask_babel/__init__.py", line 180, in default_timezone
ihatemoney    |     return timezone(self.app.config['BABEL_DEFAULT_TIMEZONE'])
ihatemoney    |   File "/usr/local/lib/python3.7/site-packages/pytz/__init__.py", line 188, in timezone
ihatemoney    |     raise UnknownTimeZoneError(zone)
ihatemoney    | pytz.exceptions.UnknownTimeZoneError: '<babel.localtime._FallbackLocalTimezone object at 0x7f055fb2fd50>'
```
</details>

This error occurs with and without any data in the 'test' project.

the docker host locale is set as follow (not sure if relevant?)

<details>
  <summary>Click to show</summary>

```bash
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
</details>

This is my docker-compose.yaml and env file setting up ihatemoney:

<details>
  <summary>Click to show docker-compose.yaml</summary>

```yaml
version: '3.3'
services:
    ihatemoney:
        container_name: ihatemoney
        volumes:
            - '/mnt/nas-docker/volumes/ihatemoney/:/database'
        env_file:
            - ./env
        ports:
                - '7000:8000'
        command: -w 3
        image: ihatemoney 
```
</details>

<details>
  <summary>Click to show env</summary>

``` bash
NIGHTLY=true

SECRET_KEY=XXXX

ACTIVATE_DEMO_PROJECT=False

ACTIVATE_ADMIN_DASHBOARD=True
# asdf
ADMIN_PASSWORD=pbkdf2:sha256:YYYY

MAIL_SERVER=some.smtp.host.com
MAIL_PORT=597
MAIL_USE_TLS=True
MAIL_USE_SSL=False
MAIL_DEFAULT_SENDER=(\"Budget Manager\", \"somehting@somehost.com\")
MAIL_DEBUG=app.debug
MAIL_USERNAME=somehting@somehost.com
MAIL_PASSWORD=ZZZ
```
</details>

Last but not least the startup log. Nothing special here. Maybe its relevant.

<details>
  <summary>Click to show start log</summary>
  
```bash
$ docker-compose up -d && docker-compose logs -f
ihatemoney is up-to-date
Attaching to ihatemoney
ihatemoney    | Cloning...
ihatemoney    | Cloning into '/ihatemoney'...
ihatemoney    | Done cloning.
ihatemoney    | Obtaining file:///ihatemoney
ihatemoney    | Collecting blinker~=1.4
ihatemoney    |   Downloading blinker-1.4.tar.gz (111 kB)
ihatemoney    | Collecting cachetools~=4.1
ihatemoney    |   Downloading cachetools-4.2.1-py3-none-any.whl (12 kB)
ihatemoney    | Collecting debts~=0.5
ihatemoney    |   Downloading debts-0.5.tar.gz (3.9 kB)
ihatemoney    | Collecting email_validator~=1.0
ihatemoney    |   Downloading email_validator-1.1.2-py2.py3-none-any.whl (17 kB)
ihatemoney    | Collecting Flask-Babel~=1.0
ihatemoney    |   Downloading Flask_Babel-1.0.0-py3-none-any.whl (9.5 kB)
ihatemoney    | Collecting Flask-Cors~=3.0
ihatemoney    |   Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
ihatemoney    | Collecting Flask-Mail~=0.9
ihatemoney    |   Downloading Flask-Mail-0.9.1.tar.gz (45 kB)
ihatemoney    | Collecting Flask-Migrate>=2.5.3
ihatemoney    |   Downloading Flask_Migrate-2.6.0-py2.py3-none-any.whl (13 kB)
ihatemoney    | Collecting Flask-RESTful~=0.3
ihatemoney    |   Downloading Flask_RESTful-0.3.8-py2.py3-none-any.whl (25 kB)
ihatemoney    | Collecting Flask-Script~=2.0
ihatemoney    |   Downloading Flask-Script-2.0.6.tar.gz (43 kB)
ihatemoney    | Collecting Flask-SQLAlchemy~=2.4
ihatemoney    |   Downloading Flask_SQLAlchemy-2.4.4-py2.py3-none-any.whl (17 kB)
ihatemoney    | Collecting Flask-WTF>=0.14.3,~=0.14
ihatemoney    |   Downloading Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
ihatemoney    | Collecting WTForms<2.3,~=2.2.1
ihatemoney    |   Downloading WTForms-2.2.1-py2.py3-none-any.whl (166 kB)
ihatemoney    | Collecting Flask~=1.1
ihatemoney    |   Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
ihatemoney    | Collecting itsdangerous~=1.1
ihatemoney    |   Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
ihatemoney    | Collecting Jinja2~=2.11
ihatemoney    |   Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
ihatemoney    | Collecting requests~=2.22
ihatemoney    |   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
ihatemoney    | Collecting SQLAlchemy-Continuum~=1.3
ihatemoney    |   Downloading SQLAlchemy-Continuum-1.3.11.tar.gz (77 kB)
ihatemoney    | Collecting idna>=2.0.0
ihatemoney    |   Downloading idna-3.1-py3-none-any.whl (58 kB)
ihatemoney    | Collecting dnspython>=1.15.0
ihatemoney    |   Downloading dnspython-2.1.0-py3-none-any.whl (241 kB)
ihatemoney    | Collecting Werkzeug>=0.15
ihatemoney    |   Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
ihatemoney    | Collecting click>=5.1
ihatemoney    |   Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
ihatemoney    | Collecting pytz
ihatemoney    |   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
ihatemoney    | Collecting Babel>=2.3
ihatemoney    |   Downloading Babel-2.9.0-py2.py3-none-any.whl (8.8 MB)
ihatemoney    | Collecting Six
ihatemoney    |   Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
ihatemoney    | Collecting alembic>=0.7
ihatemoney    |   Downloading alembic-1.5.3.tar.gz (1.1 MB)
ihatemoney    | Collecting SQLAlchemy>=1.3.0
ihatemoney    |   Downloading SQLAlchemy-1.3.23.tar.gz (6.3 MB)
ihatemoney    | Collecting Mako
ihatemoney    |   Downloading Mako-1.1.4.tar.gz (479 kB)
ihatemoney    | Collecting python-editor>=0.3
ihatemoney    |   Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
ihatemoney    | Collecting python-dateutil
ihatemoney    |   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
ihatemoney    | Collecting aniso8601>=0.82
ihatemoney    |   Downloading aniso8601-8.1.1-py2.py3-none-any.whl (44 kB)
ihatemoney    | Collecting MarkupSafe>=0.23
ihatemoney    |   Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
ihatemoney    | Collecting urllib3<1.27,>=1.21.1
ihatemoney    |   Downloading urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
ihatemoney    | Collecting chardet<5,>=3.0.2
ihatemoney    |   Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
ihatemoney    | Collecting idna>=2.0.0
ihatemoney    |   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
ihatemoney    | Collecting certifi>=2017.4.17
ihatemoney    |   Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
ihatemoney    | Collecting SQLAlchemy-Utils>=0.30.12
ihatemoney    |   Downloading SQLAlchemy-Utils-0.36.8.tar.gz (138 kB)
ihatemoney    | Building wheels for collected packages: blinker, debts, Flask-Mail, alembic, Flask-Script, MarkupSafe, SQLAlchemy, SQLAlchemy-Continuum, SQLAlchemy-Utils, Mako
ihatemoney    |   Building wheel for blinker (setup.py): started
ihatemoney    |   Building wheel for blinker (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13451 sha256=2ad56b8a5264a3ec114b8bb079396a10030eb5f84ca588858d66ba12c3c89e0e
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/22/f5/18/df711b66eb25b21325c132757d4314db9ac5e8dabeaf196eab
ihatemoney    |   Building wheel for debts (setup.py): started
ihatemoney    |   Building wheel for debts (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for debts: filename=debts-0.5-py3-none-any.whl size=4655 sha256=fcfa13e4f08693c4b7a296ecaa15597bf0c53442abd0fab674e872d880d7f28f
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/54/7d/3a/90babdd2d3bfd2ff5bf43229fabea18f70975e416673ecf9fb
ihatemoney    |   Building wheel for Flask-Mail (setup.py): started
ihatemoney    |   Building wheel for Flask-Mail (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for Flask-Mail: filename=Flask_Mail-0.9.1-py3-none-any.whl size=7568 sha256=558d889b625d249d82e97252575a5e4606e69df5fabf212c8ff60c7a6c5904d0
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/c3/46/1d/34849a40eb7e4b84d8c794ef49bce76c7d9e968cf0400f2e5c
ihatemoney    |   Building wheel for alembic (setup.py): started
ihatemoney    |   Building wheel for alembic (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for alembic: filename=alembic-1.5.3-py2.py3-none-any.whl size=155547 sha256=02eb0ca628dacc6b5db23e83c4f1e79f944a0f7eeb3299fbdc029eeb801717b0
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/4d/c7/da/a809395ccd722e350e890051972e0ca569d116289a08ae0064
ihatemoney    |   Building wheel for Flask-Script (setup.py): started
ihatemoney    |   Building wheel for Flask-Script (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for Flask-Script: filename=Flask_Script-2.0.6-py3-none-any.whl size=14015 sha256=f2e59303da1c4c4236de324de4c65c56e2642adbe9f02f2b15e841711d0bf62c
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/b5/fb/6b/01ea56e8a6486540ebe086676c8b3a823f1bbcc830df0cd4f0
ihatemoney    |   Building wheel for MarkupSafe (setup.py): started
ihatemoney    |   Building wheel for MarkupSafe (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for MarkupSafe: filename=MarkupSafe-1.1.1-cp37-cp37m-linux_x86_64.whl size=16911 sha256=f3c7939a8ca64c6da9ecb8ad93e48f01751fdca2fa5196120170f7ad5c0acefb
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/b9/d9/ae/63bf9056b0a22b13ade9f6b9e08187c1bb71c47ef21a8c9924
ihatemoney    |   Building wheel for SQLAlchemy (setup.py): started
ihatemoney    |   Building wheel for SQLAlchemy (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for SQLAlchemy: filename=SQLAlchemy-1.3.23-cp37-cp37m-linux_x86_64.whl size=1214867 sha256=85eef214d5f79398c10a0e035e9c7a8a3070fee951dfb9257c8c797d0634943b
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/a7/62/40/b146ab834a41a00bac916e06f1cf236893145851994ae36e73
ihatemoney    |   Building wheel for SQLAlchemy-Continuum (setup.py): started
ihatemoney    |   Building wheel for SQLAlchemy-Continuum (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for SQLAlchemy-Continuum: filename=SQLAlchemy_Continuum-1.3.11-py3-none-any.whl size=45029 sha256=6447e40e8d1a2c5eddb9027be650978fe5e265b886f070d73060f3c691fc225f
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/2e/b9/82/5ec4e9464fe89d88f8ed643c66e2bfbcb0da78ddea176be80d
ihatemoney    |   Building wheel for SQLAlchemy-Utils (setup.py): started
ihatemoney    |   Building wheel for SQLAlchemy-Utils (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for SQLAlchemy-Utils: filename=SQLAlchemy_Utils-0.36.8-py2.py3-none-any.whl size=93220 sha256=54d386f344ad4419490bc55b481ac998127e411f32a6a14e86bd2a24eb26bc8f
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/29/c3/6b/495f824c202b91e5dc231e802afa062910f229ad2131588a96
ihatemoney    |   Building wheel for Mako (setup.py): started
ihatemoney    |   Building wheel for Mako (setup.py): finished with status 'done'
ihatemoney    |   Created wheel for Mako: filename=Mako-1.1.4-py2.py3-none-any.whl size=75675 sha256=6831ab82608edaab83766500bd70637fe256d6592b9b4766c1ef4b8afd0d77d3
ihatemoney    |   Stored in directory: /tmp/pip-ephem-wheel-cache-aqakndtl/wheels/2a/60/32/02a16820f96c067f6161ef35c21559f8db52c4158d6602b438
ihatemoney    | Successfully built blinker debts Flask-Mail alembic Flask-Script MarkupSafe SQLAlchemy SQLAlchemy-Continuum SQLAlchemy-Utils Mako
ihatemoney    | Installing collected packages: MarkupSafe, Werkzeug, Six, Jinja2, itsdangerous, click, SQLAlchemy, pytz, python-editor, python-dateutil, Mako, Flask, WTForms, urllib3, SQLAlchemy-Utils, idna, Flask-SQLAlchemy, dnspython, chardet, certifi, blinker, Babel, aniso8601, alembic, SQLAlchemy-Continuum, requests, Flask-WTF, Flask-Script, Flask-RESTful, Flask-Migrate, Flask-Mail, Flask-Cors, Flask-Babel, email-validator, debts, cachetools, ihatemoney
ihatemoney    |   Running setup.py develop for ihatemoney
ihatemoney    | Successfully installed Babel-2.9.0 Flask-1.1.2 Flask-Babel-1.0.0 Flask-Cors-3.0.10 Flask-Mail-0.9.1 Flask-Migrate-2.6.0 Flask-RESTful-0.3.8 Flask-SQLAlchemy-2.4.4 Flask-Script-2.0.6 Flask-WTF-0.14.3 Jinja2-2.11.3 Mako-1.1.4 MarkupSafe-1.1.1 SQLAlchemy-1.3.23 SQLAlchemy-Continuum-1.3.11 SQLAlchemy-Utils-0.36.8 Six-1.15.0 WTForms-2.2.1 Werkzeug-1.0.1 alembic-1.5.3 aniso8601-8.1.1 blinker-1.4 cachetools-4.2.1 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 debts-0.5 dnspython-2.1.0 email-validator-1.1.2 idna-2.10 ihatemoney itsdangerous-1.1.0 python-dateutil-2.8.1 python-editor-1.0.4 pytz-2021.1 requests-2.25.1 urllib3-1.26.3
ihatemoney    | [2021-02-02 13:17:12 +0000] [1] [INFO] Starting gunicorn 20.0.4
ihatemoney    | [2021-02-02 13:17:12 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
ihatemoney    | [2021-02-02 13:17:12 +0000] [1] [INFO] Using worker: sync
ihatemoney    | [2021-02-02 13:17:12 +0000] [90] [INFO] Booting worker with pid: 90
ihatemoney    | [2021-02-02 13:17:12 +0000] [91] [INFO] Booting worker with pid: 91
ihatemoney    | [2021-02-02 13:17:12 +0000] [92] [INFO] Booting worker with pid: 92
ihatemoney    | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
ihatemoney    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ihatemoney    | INFO  [alembic.runtime.migration] Running upgrade a67119aa3ee5 -> 6c6fb2b7f229, empty message
ihatemoney    | INFO  [alembic.runtime.migration] Running upgrade 6c6fb2b7f229 -> 2dcb0c0048dc, autologger
ihatemoney    | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
ihatemoney    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ihatemoney    | INFO  [alembic.runtime.migration] Running upgrade 2dcb0c0048dc -> cb038f79982e, sqlite_autoincrement
ihatemoney    | INFO  [alembic.runtime.migration] Running upgrade cb038f79982e -> 927ed575acbd, Add currencies
ihatemoney    | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
ihatemoney    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```
</details>

Overall not sure what I mis-configured. Can anyone point me to what I am doing wrong? Thanks!

**Comment by nkoester** [comment]
I have no idea how i managed to scroll past the ```BABEL_DEFAULT_TIMEZONE``` configuration documentation. But setting it to "Europe/Paris" as mentioned (or even "UTC") does not work :( The issue persists. 

Maybe a default setting could be used in case the system timezone is not set? I can imagine other users with docker will experience this issue as well.

**Comment by nkoester** [comment]
It seems the entrypoint.sh is not forwarding the BABEL_DEFAULT_TIMEZONE variable:

https://github.com/spiral-project/ihatemoney/blob/master/conf/entrypoint.sh
