### ISSUE TITLE
AttributeError in worker process [Docker]

### ISSUE THREAD

**Issue by ToadCast** [spiral-project/ihatemoney#728]
Hi, after fixing my issue with building process (cf. https://github.com/spiral-project/ihatemoney/issues/726) I still can not use the docker image because of an `AttributeError`. Here is my command to launch my instance:
```
docker run -p 8000:8000 -e SECRET_KEY="....." -e ADMIN_PASSWORD="pbkdf2:sha256:....." -v /var/lib/ihatemoney-db:/database ihatemoney
```
and the error:
```
Successfully built ihatemoney blinker Flask-Babel Flask-Mail Flask-Script MarkupSafe SQLAlchemy greenlet
Installing collected packages: zipp, typing-extensions, MarkupSafe, Werkzeug, six, Jinja2, itsdangerous, importlib-metadata, greenlet, click, SQLAlchemy, pytz, python-editor, python-dateutil, Mako, Flask, WTForms, idna, Flask-SQLAlchemy, dnspython, blinker, Babel, aniso8601, alembic, Flask-WTF, Flask-Script, Flask-RESTful, Flask-Migrate, Flask-Mail, Flask-Cors, Flask-Babel, email-validator, ihatemoney
Successfully installed Babel-2.9.0 Flask-1.1.1 Flask-Babel-0.12.2 Flask-Cors-3.0.8 Flask-Mail-0.9.1 Flask-Migrate-2.5.3 Flask-RESTful-0.3.7 Flask-SQLAlchemy-2.4.0 Flask-Script-2.0.6 Flask-WTF-0.14.3 Jinja2-2.10.1 Mako-1.1.4 MarkupSafe-1.1.1 SQLAlchemy-1.4.4 WTForms-2.2.1 Werkzeug-0.16.1 alembic-1.5.8 aniso8601-9.0.1 blinker-1.4 click-7.1.2 dnspython-2.1.0 email-validator-1.0.4 greenlet-1.0.0 idna-3.1 ihatemoney-4.1.5 importlib-metadata-3.10.0 itsdangerous-1.1.0 python-dateutil-2.8.1 python-editor-1.0.4 pytz-2021.1 six-1.14.0 typing-extensions-3.7.4.3 zipp-3.4.1
[2021-04-01 12:19:34 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-04-01 12:19:34 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2021-04-01 12:19:34 +0000] [1] [INFO] Using worker: sync
[2021-04-01 12:19:34 +0000] [89] [INFO] Booting worker with pid: 89
[2021-04-01 12:19:35 +0000] [89] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/ihatemoney/wsgi.py", line 3, in <module>
    application = create_app()
  File "/usr/local/lib/python3.7/site-packages/ihatemoney/run.py", line 132, in create_app
    setup_database(app)
  File "/usr/local/lib/python3.7/site-packages/ihatemoney/run.py", line 44, in setup_database
    if _pre_alembic_db():
  File "/usr/local/lib/python3.7/site-packages/ihatemoney/run.py", line 26, in _pre_alembic_db
    con = db.engine.connect()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 937, in engine
    return self.get_engine()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 560, in get_engine
    options = self.get_options(sa_url, echo)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 575, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 908, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
[2021-04-01 12:19:35 +0000] [89] [INFO] Worker exiting (pid: 89)
[2021-04-01 12:19:36 +0000] [1] [INFO] Shutting down: Master
[2021-04-01 12:19:36 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by ilkohoffmann** [comment]
Same problem here

**Comment by TiDjY35** [comment]
also same problem

**Comment by ilkohoffmann** [comment]
The issue seems to be related to

- [Stackoverflow #66644975](https://stackoverflow.com/questions/66644975/importerror-cannot-import-name-columnentity-from-sqlalchemy-orm-query)
- [Stackoverflow #66647787](https://stackoverflow.com/questions/66647787/attributeerror-cant-set-attribute-when-connecting-to-sqlite-database-with-flas)

Pinning SQL-ALchemy version to <1.3 seems to resolve the build issue and launches the app without errors. On requesting `/ `in the browser I am receiving another error though:

```
ERROR [ihatemoney.run] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/ihatemoney/ihatemoney/web.py", line 256, in home
    project_form = ProjectForm()
  File "/usr/local/lib/python3.9/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/ihatemoney/ihatemoney/forms.py", line 116, in __init__
    for currency_name in self.currency_helper.get_currencies()
  File "/ihatemoney/ihatemoney/currency_convertor.py", line 31, in get_currencies
    for rate in self.get_rates()
  File "/usr/local/lib/python3.9/site-packages/cachetools/decorators.py", line 22, in wrapper
    v = func(*args, **kwargs)
  File "/ihatemoney/ihatemoney/currency_convertor.py", line 24, in get_rates
    rates = requests.get(self.api_url).json()["rates"]
KeyError: 'rates'
```

**Comment by ilkohoffmann** [comment]
Seems like the API `http://api.exchangeratesapi.io`, which is used by the class `CurrencyConverter`, is not allowed to be used without an API Key (anymore?). Not a proper solution, but replacing line 24 `rates = requests.get(self.api_url).json()["rates"]` with `rates = dict()` fixes that issue for me.

**Comment by zorun** [comment]
Thanks for the report. Can you open a new issue for the exchangerate change?
