### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by jendrikw** [spiral-project/ihatemoney#815]
I know there are a lot of issues related to this, but I couldn't find a solution.

I'm trying to install ihatemoney on a fresh debian 10. I executed `pip3 install ihatemoney`. This is the output from pip:

```
Collecting ihatemoney==4.1.5
  Downloading https://files.pythonhosted.org/packages/05/b0/e6d9575730163d9d31a6c42f8bc789246f802a32fad7023c804f2b113289/ihatemoney-4.1.5.tar.gz (366kB)
Collecting Flask-Babel==0.12.2 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/82/b0/986b29938d4e8be7deb552ebfd1ef16c311276a59bcae10dec567a5b3d20/Flask-Babel-0.12.2.tar.gz (44kB)
Collecting Flask-Cors==3.0.8 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/78/38/e68b11daa5d613e3a91e4bf3da76c94ac9ee0d9cd515af9c1ab80d36f709/Flask_Cors-3.0.8-py2.py3-none-any.whl
Collecting Flask-Mail==0.9.1 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz (45kB)
Collecting Flask-Migrate==2.5.3 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/e5/64/c75f173ba5420f5174be6f04dfa8d8250d4808c12a9cd781e84c0b31684f/Flask_Migrate-2.5.3-py2.py3-none-any.whl
Collecting Flask-RESTful==0.3.7 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/17/44/6e490150ee443ca81d5f88b61bb4bbb133d44d75b0b716ebe92489508da4/Flask_RESTful-0.3.7-py2.py3-none-any.whl
Collecting Flask-SQLAlchemy==2.4.0 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/08/ca/582442cad71504a1514a2f053006c8bb128844133d6076a4df17117545fa/Flask_SQLAlchemy-2.4.0-py2.py3-none-any.whl
Collecting Flask-Script==2.0.6 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/00/a4/cd587b2b19f043b65bf33ceda2f6e4e6cdbd0ce18d01a52b9559781b1da6/Flask-Script-2.0.6.tar.gz (43kB)
Collecting Flask-WTF==0.14.3 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/36/a9/8c01171066bd7a524ee005d81bb4a8aa446ab178043a1ad6cb5dc8f0bd83/Flask_WTF-0.14.3-py2.py3-none-any.whl
Collecting Flask==1.1.1 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting Jinja2==2.10.1 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl (124kB)
Collecting WTForms==2.2.1 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/9f/c8/dac5dce9908df1d9d48ec0e26e2a250839fa36ea2c602cc4f85ccfeb5c65/WTForms-2.2.1-py2.py3-none-any.whl (166kB)
Collecting Werkzeug==0.16.1 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/c2/e4/a859d2fe516f466642fa5c6054fd9646271f9da26b0cac0d2f37fc858c8f/Werkzeug-0.16.1-py2.py3-none-any.whl (327kB)
Collecting blinker==1.4 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz (111kB)
Collecting email-validator==1.0.4 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/09/31/f1a496192ea2e87ec4db40dfc2f000de3fbce565e10e95f09a614127e09f/email_validator-1.0.4-py2.py3-none-any.whl
Collecting itsdangerous==1.1.0 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting six==1.14.0 (from ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting Babel>=2.3 (from Flask-Babel==0.12.2->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/aa/96/4ba93c5f40459dc850d25f9ba93f869a623e77aaecc7a9344e19c01942cf/Babel-2.9.1-py2.py3-none-any.whl (8.8MB)
Collecting alembic>=0.7 (from Flask-Migrate==2.5.3->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/d5/80/ef186e599a57d0e4cb78fc76e0bfc2e6953fa9716b2a5cf2de0117ed8eb5/alembic-1.6.5-py2.py3-none-any.whl (164kB)
Collecting pytz (from Flask-RESTful==0.3.7->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/70/94/784178ca5dd892a98f113cdd923372024dc04b8d40abe77ca76b5fb90ca6/pytz-2021.1-py2.py3-none-any.whl (510kB)
Collecting aniso8601>=0.82 (from Flask-RESTful==0.3.7->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/e3/04/e97c12dc034791d7b504860acfcdd2963fa21ae61eaca1c9d31245f812c3/aniso8601-9.0.1-py2.py3-none-any.whl (52kB)
Collecting SQLAlchemy>=0.8.0 (from Flask-SQLAlchemy==2.4.0->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/11/ed/c079a81ae2241417d61008e6874d2ee84a8cbae4e511945f4f95c1b3849f/SQLAlchemy-1.4.21-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6MB)
Collecting click>=5.1 (from Flask==1.1.1->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/76/0a/b6c5f311e32aeb3b406e03c079ade51e905ea630fc19d1262a46249c1c86/click-8.0.1-py3-none-any.whl (97kB)
Collecting MarkupSafe>=0.23 (from Jinja2==2.10.1->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/d7/56/9d9c0dc2b0f5dc342ff9c7df31c523cc122947970b5ea943b2311be0c391/MarkupSafe-2.0.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting idna>=2.0.0 (from email-validator==1.0.4->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/d7/77/ff688d1504cdc4db2a938e2b7b9adee5dd52e34efbd2431051efc9984de9/idna-3.2-py3-none-any.whl (59kB)
Collecting dnspython>=1.15.0 (from email-validator==1.0.4->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/f5/2d/ae9e172b4e5e72fa4b3cfc2517f38b602cc9ba31355f9669c502b4e9c458/dnspython-2.1.0-py3-none-any.whl (241kB)
Collecting Mako (from alembic>=0.7->Flask-Migrate==2.5.3->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/f3/54/dbc07fbb20865d3b78fdb7cf7fa713e2cba4f87f71100074ef2dc9f9d1f7/Mako-1.1.4-py2.py3-none-any.whl (75kB)
Collecting python-editor>=0.3 (from alembic>=0.7->Flask-Migrate==2.5.3->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/c6/d3/201fc3abe391bbae6606e6f1d598c15d367033332bd54352b12f35513717/python_editor-1.0.4-py3-none-any.whl
Collecting python-dateutil (from alembic>=0.7->Flask-Migrate==2.5.3->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247kB)
Collecting greenlet!=0.4.17; python_version >= \"3\" (from SQLAlchemy>=0.8.0->Flask-SQLAlchemy==2.4.0->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/ee/d3/39767bcd86bad5b64dfe3e19a7ce07ecaa33a47cd434a222221db56adba6/greenlet-1.1.0-cp37-cp37m-manylinux1_x86_64.whl (160kB)
Collecting importlib-metadata; python_version < \"3.8\" (from SQLAlchemy>=0.8.0->Flask-SQLAlchemy==2.4.0->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/3f/e1/e5bba549a033adf77448699a34ecafc7a32adaeeb4369396b35f56d5cc3e/importlib_metadata-4.6.1-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < \"3.8\"->SQLAlchemy>=0.8.0->Flask-SQLAlchemy==2.4.0->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/92/d9/89f433969fb8dc5b9cbdd4b4deb587720ec1aeb59a020cf15002b9593eef/zipp-3.5.0-py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < \"3.8\" (from importlib-metadata; python_version < \"3.8\"->SQLAlchemy>=0.8.0->Flask-SQLAlchemy==2.4.0->ihatemoney==4.1.5)
  Downloading https://files.pythonhosted.org/packages/2e/35/6c4fff5ab443b57116cb1aad46421fb719bed2825664e8fe77d66d99bcbc/typing_extensions-3.10.0.0-py3-none-any.whl
Building wheels for collected packages: ihatemoney, Flask-Babel, Flask-Mail, Flask-Script, blinker
  Running setup.py bdist_wheel for ihatemoney: started
  Running setup.py bdist_wheel for ihatemoney: finished with status 'error'
  Complete output from command /opt/ihatemoney/venv/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-install-6r1s0e3k/ihatemoney/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/pip-wheel-152cydgw --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Running setup.py clean for ihatemoney
  Running setup.py bdist_wheel for Flask-Babel: started
  Running setup.py bdist_wheel for Flask-Babel: finished with status 'error'
  Complete output from command /opt/ihatemoney/venv/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-install-6r1s0e3k/Flask-Babel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/pip-wheel-_ryd4h0a --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Running setup.py clean for Flask-Babel
  Running setup.py bdist_wheel for Flask-Mail: started
  Running setup.py bdist_wheel for Flask-Mail: finished with status 'error'
  Complete output from command /opt/ihatemoney/venv/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-install-6r1s0e3k/Flask-Mail/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/pip-wheel-dtuvg6rf --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Running setup.py clean for Flask-Mail
  Running setup.py bdist_wheel for Flask-Script: started
  Running setup.py bdist_wheel for Flask-Script: finished with status 'error'
  Complete output from command /opt/ihatemoney/venv/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-install-6r1s0e3k/Flask-Script/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/pip-wheel-lpwjruif --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Running setup.py clean for Flask-Script
  Running setup.py bdist_wheel for blinker: started
  Running setup.py bdist_wheel for blinker: finished with status 'error'
  Complete output from command /opt/ihatemoney/venv/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-install-6r1s0e3k/blinker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/pip-wheel-y20cdeou --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Running setup.py clean for blinker
Failed to build ihatemoney Flask-Babel Flask-Mail Flask-Script blinker
Installing collected packages: pytz, Babel, itsdangerous, zipp, typing-extensions, importlib-metadata, click, Werkzeug, MarkupSafe, Jinja2, Flask, Flask-Babel, six, Flask-Cors, blinker, Flask-Mail, greenlet, SQLAlchemy, Flask-SQLAlchemy, Mako, python-editor, python-dateutil, alembic, Flask-Migrate, aniso8601, Flask-RESTful, Flask-Script, WTForms, Flask-WTF, idna, dnspython, email-validator, ihatemoney
  Running setup.py install for Flask-Babel: started
    Running setup.py install for Flask-Babel: finished with status 'done'
  Running setup.py install for blinker: started
    Running setup.py install for blinker: finished with status 'done'
  Running setup.py install for Flask-Mail: started
    Running setup.py install for Flask-Mail: finished with status 'done'
  Running setup.py install for Flask-Script: started
    Running setup.py install for Flask-Script: finished with status 'done'
  Running setup.py install for ihatemoney: started
    Running setup.py install for ihatemoney: finished with status 'done'
Successfully installed Babel-2.9.1 Flask-1.1.1 Flask-Babel-0.12.2 Flask-Cors-3.0.8 Flask-Mail-0.9.1 Flask-Migrate-2.5.3 Flask-RESTful-0.3.7 Flask-SQLAlchemy-2.4.0 Flask-Script-2.0.6 Flask-WTF-0.14.3 Jinja2-2.10.1 Mako-1.1.4 MarkupSafe-2.0.1 SQLAlchemy-1.4.21 WTForms-2.2.1 Werkzeug-0.16.1 alembic-1.6.5 aniso8601-9.0.1 blinker-1.4 click-8.0.1 dnspython-2.1.0 email-validator-1.0.4 greenlet-1.1.0 idna-3.2 ihatemoney-4.1.5 importlib-metadata-4.6.1 itsdangerous-1.1.0 python-dateutil-2.8.2 python-editor-1.0.4 pytz-2021.1 six-1.14.0 typing-extensions-3.10.0.0 zipp-3.5.0"
```

Running `ihatemoney` produces the following error message:

```
/opt/ihatemoney/venv/lib/python3.7/site-packages/ihatemoney/run.py:81: UserWarning: Running a server without changing the SECRET_KEY can lead to user impersonation. Please update your configuration file.
  UserWarning
/opt/ihatemoney/venv/lib/python3.7/site-packages/ihatemoney/run.py:34: UserWarning: The database is currently stored in /tmp and might be lost at next reboot.
  'The database is currently stored in /tmp and might be lost at '
Traceback (most recent call last):
  File "/opt/ihatemoney/venv/bin/ihatemoney", line 11, in <module>
    load_entry_point('ihatemoney==4.1.5', 'console_scripts', 'ihatemoney')()
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/ihatemoney/manage.py", line 76, in main
    app = create_app()
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/ihatemoney/run.py", line 132, in create_app
    setup_database(app)
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/ihatemoney/run.py", line 44, in setup_database
    if _pre_alembic_db():
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/ihatemoney/run.py", line 26, in _pre_alembic_db
    con = db.engine.connect()
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 937, in engine
    return self.get_engine()
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 560, in get_engine
    options = self.get_options(sa_url, echo)
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 575, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/opt/ihatemoney/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 908, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
```

What can I do to fix this error?

**Comment by zorun** [comment]
It's because the current release doesn't pin SQLAlchemy and the new version is not compatible. You can fix it with:
```
pip3 install 'SQLAlchemy>=1.3,<1.4'
```

We are nearing a new major release, it will work fine once it's out.

I have just added this workaround to the documentation: https://ihatemoney.readthedocs.io/en/latest/installation.html#install
