### ISSUE TITLE
can't start server after building

### ISSUE THREAD

**Issue by unnameduser2** [spiral-project/ihatemoney#830]
Hi,

I've tried now to get ihatemoney running on several different machines, but all with the same problem, despite if trying with root or a normal user account.
Tried with these instructions: https://ihatemoney.readthedocs.io/en/latest/installation.html

Tested OS so far: Debian 10.10, Ubuntu 20.4.3 LTS, CentOS 8.4.2105

a) before "pip install ihatemoney" I need to run "pip install wheel", otherwise I get some messages "Failed building wheel for..."

b) next step "ihatemoney runserver" crashes with following:
`(ihatemoney) user@nas:~/ihatemoney$ ihatemoney runserver
/home/user/ihatemoney/lib/python3.7/site-packages/ihatemoney/run.py:81: UserWarning: Running a server without changing the SECRET_KEY can lead to user impersonation. Please update your configuration file.
  UserWarning
/home/user/ihatemoney/lib/python3.7/site-packages/ihatemoney/run.py:34: UserWarning: The database is currently stored in /tmp and might be lost at next reboot.
  'The database is currently stored in /tmp and might be lost at '
Traceback (most recent call last):
  File "/home/user/ihatemoney/bin/ihatemoney", line 10, in <module>
    sys.exit(main())
  File "/home/user/ihatemoney/lib/python3.7/site-packages/ihatemoney/manage.py", line 76, in main
    app = create_app()
  File "/home/user/ihatemoney/lib/python3.7/site-packages/ihatemoney/run.py", line 132, in create_app
    setup_database(app)
  File "/home/user/ihatemoney/lib/python3.7/site-packages/ihatemoney/run.py", line 44, in setup_database
    if _pre_alembic_db():
  File "/home/user/ihatemoney/lib/python3.7/site-packages/ihatemoney/run.py", line 26, in _pre_alembic_db
    con = db.engine.connect()
  File "/home/user/ihatemoney/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 937, in engine
    return self.get_engine()
  File "/home/user/ihatemoney/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/home/user/ihatemoney/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 560, in get_engine
    options = self.get_options(sa_url, echo)
  File "/home/user/ihatemoney/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 575, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/user/ihatemoney/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 908, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
`

Also when trying to generate the default config, nothing happens (or just an empty cfg-file is returned).

As mentioned I've already tested three different distributions (with different python versions) and all dependencies from the instructions are installed, I guess there is somethihng broken. Or what am I missing?

Thanks for any hints/help

**Comment by zorun** [comment]
You said you followed the documentation, did you see the warning about needing to install a specific version of sqlalchemy?
