### ISSUE TITLE
decimal.InvalidOperation

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#930]
Not sure what's causing this, but :
```
^[[AERROR [ihatemoney.run] Exception on /demo/ [GET]
Traceback (most recent call last):
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/web.py", line 677, in list_bills
    current_view="list_bills",
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/templates/list_bills.html", line 4, in top-level template code
    {{ amount|currency(currency) }} ({{ _("%(amount)s each", amount=bill.pay_each_default(amount)|currency(currency)) }})
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/templates/sidebar_table_layout.html", line 42, in top-level template code
    {% if balance[member.id] | round(2) > 0 %}+{% endif %}{{ balance[member.id]|currency }}
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/templates/layout.html", line 116, in top-level template code
    {% block body %}
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/templates/sidebar_table_layout.html", line 52, in block 'body'
    {% block sidebar %}{% endblock %}
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/templates/list_bills.html", line 48, in block 'sidebar'
    {{ balance_table(member_edit=True) }}
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/templates/sidebar_table_layout.html", line 42, in template
    {% if balance[member.id] | round(2) > 0 %}+{% endif %}{{ balance[member.id]|currency }}
  File "/home/ihatemoney/ihatemoney.org/ihatemoney/ihatemoney/run.py", line 206, in currency
    **kwargs,
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/flask_babel/__init__.py", line 483, in format_currency
    format_type=format_type
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/babel/numbers.py", line 521, in format_currency
    decimal_quantization=decimal_quantization)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/babel/numbers.py", line 996, in apply
    number = self._quantize_value(value, locale, frac_prec)
  File "/home/ihatemoney/ihatemoney.org/venv/lib/python3.7/site-packages/babel/numbers.py", line 1065, in _quantize_value
    rounded = value.quantize(quantum)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Comment by Glandos** [comment]
It was caused by #957
